common:
  random_state: 42
  max_iter: 100

data:
  # image: data/Bunky.png        # vstupní snímek k segmentaci
  image: data/Bunky_real.png # alternativní snímek — odkomentujte a zakomentujte řádek výše

kmeans:
  k: 5
  initializer: kmeans++        # možnosti: random_uniform | forgy | kmeans++

fuzzy_cmeans:
  k: 5
  q: 2.0                       # parametr fuzifikace (pouze FCM)
  initializer: random_uniform
